### ISSUE TITLE
Packagist release with licence included

### ISSUE THREAD

**Issue by vintagesucks** [pixelfear/composer-dist-plugin#10]
Hi, thanks for adding the license to `composer.json` in #8!

Could you tag a new release so that the licence information also reaches [Packagist](https://packagist.org/packages/pixelfear/composer-dist-plugin)? We check the licences of our packages in our CI and get a (somewhat) annoying warning¹ because no licence is detected. 😅 

---

¹ `There is no license information available for the latest version (v0.1.5) of this package.`

**Comment by jasonvarga** [comment]
Oops sorry about that! I've just tagged it.
